name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: '8.1'

      - name: Run tests
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          php -v
          ./vendor/bin/phpunit test/
