# Skip AmountInCents.
- Amount
- AstroPayFinancialNumbers
- AstroPayMethodCodec
- FiscalNumber
- DonorEmail
- DummyFiscalNumber # see class comment
- DonorFullName
- StreetAddress
# Signature calculation must come last
- AstroPaySignature
