language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

# https://travis-ci.community/t/the-preinstalled-version-of-phpunit-is-incompatible-with-php/3704/2
script: ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: nightly

sudo: false
