language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

before_script:
  ## Composer
  - composer self-update
  - composer install --prefer-source --no-interaction --dev --ignore-platform-reqs

script: phpunit

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: 5.5
    - php: 5.6

sudo: false
