#
# this file provides configuration for Travis Continuous Integration
#

language: php

dist: trusty

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer require --dev --no-update phpunit/phpunit ~4; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" || $TRAVIS_PHP_VERSION == "hhvm" ]]; then composer require --dev --no-update phpunit/phpunit ~5; fi

install: composer install
 
matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm

script: vendor/bin/phpunit --coverage-text -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

