cb:
    countries:
        FR: true
    group: cc
    logo: card-cb-lg.png
visa:
    countries:
        CA: true
        FR: true
        GB: true
        IL: true
        JP: true
        UA: true
        US: true
    group: cc
    logo: card-visa-lg.png
jcb:
    countries: {}
        # Disabled for T140691
        # JP: true
    group: cc
    logo: card-jcb-lg.png
mc:
    countries:
        CA: true
        FR: true
        GB: true
        IL: true
        JP: true
        UA: true
        US: true
    group: cc
    logo: card-mastercard.png
    logo_hd:
        2x: card-mastercard_2x.png
        3x: card-mastercard_3x.png
amex:
    countries:
        CA: true
        FR: true
        GB: true
        IL: true
        UA: true
        US: true
    group: cc
    logo: card-amex-lg.png
discover:
    countries:
        IL: true
        US: true
    group: cc
    logo: card-discover-lg.png


