<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'PHPQueue' => array($vendorDir . '/coderkungfu/php-queue/src'),
    'Drush\\' => array($vendorDir . '/drush/drush/lib'),
    'Dflydev\\DotAccessData' => array($vendorDir . '/dflydev/dot-access-data/src'),
    'Consolidation\\' => array($vendorDir . '/drush/drush/lib'),
    'Clio' => array($vendorDir . '/clio/clio/src'),
);
