<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'SmashPig\\' => array($vendorDir . '/wikimedia/smash-pig'),
    'Predis\\' => array($vendorDir . '/predis/predis/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
);
