<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'AdyenAdapter' => $vendorDir . '/wikimedia/donation-interface/adyen_gateway/adyen.adapter.php',
    'AdyenGateway' => $vendorDir . '/wikimedia/donation-interface/adyen_gateway/adyen_gateway.body.php',
    'AdyenGatewayResult' => $vendorDir . '/wikimedia/donation-interface/adyen_gateway/adyen_resultswitcher.body.php',
    'AmazonAdapter' => $vendorDir . '/wikimedia/donation-interface/amazon_gateway/amazon.adapter.php',
    'AmazonGateway' => $vendorDir . '/wikimedia/donation-interface/amazon_gateway/amazon_gateway.body.php',
    'CurrencyRates' => $vendorDir . '/wikimedia/donation-interface/gateway_common/CurrencyRates.php',
    'DataValidator' => $vendorDir . '/wikimedia/donation-interface/gateway_common/DataValidator.php',
    'DonationApi' => $vendorDir . '/wikimedia/donation-interface/gateway_common/donation.api.php',
    'DonationData' => $vendorDir . '/wikimedia/donation-interface/gateway_common/DonationData.php',
    'EncodingMangler' => $vendorDir . '/wikimedia/donation-interface/gateway_common/EncodingMangler.php',
    'GatewayAdapter' => $vendorDir . '/wikimedia/donation-interface/gateway_common/gateway.adapter.php',
    'GatewayPage' => $vendorDir . '/wikimedia/donation-interface/gateway_common/GatewayPage.php',
    'GatewayType' => $vendorDir . '/wikimedia/donation-interface/gateway_common/gateway.adapter.php',
    'GlobalCollectAdapter' => $vendorDir . '/wikimedia/donation-interface/globalcollect_gateway/globalcollect.adapter.php',
    'GlobalCollectGateway' => $vendorDir . '/wikimedia/donation-interface/globalcollect_gateway/globalcollect_gateway.body.php',
    'GlobalCollectGatewayResult' => $vendorDir . '/wikimedia/donation-interface/globalcollect_gateway/globalcollect_resultswitcher.body.php',
    'GlobalCollectOrphanAdapter' => $vendorDir . '/wikimedia/donation-interface/globalcollect_gateway/scripts/orphan_adapter.php',
    'GlobalCollectOrphanRectifier' => $vendorDir . '/wikimedia/donation-interface/globalcollect_gateway/scripts/orphans.php',
    'MWException' => $vendorDir . '/wikimedia/donation-interface/gateway_common/MWException.drupal.php',
    'NationalCurrencies' => $vendorDir . '/wikimedia/donation-interface/gateway_common/NationalCurrencies.php',
    'PHPMailer' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
    'POP3' => $vendorDir . '/phpmailer/phpmailer/class.pop3.php',
    'PaymentMethod' => $vendorDir . '/wikimedia/donation-interface/gateway_common/PaymentMethod.php',
    'PaymentResult' => $vendorDir . '/wikimedia/donation-interface/gateway_common/PaymentResult.php',
    'PaypalAdapter' => $vendorDir . '/wikimedia/donation-interface/paypal_gateway/paypal.adapter.php',
    'PaypalGateway' => $vendorDir . '/wikimedia/donation-interface/paypal_gateway/paypal_gateway.body.php',
    'PaypalGatewayResult' => $vendorDir . '/wikimedia/donation-interface/paypal_gateway/paypal_resultswitcher.body.php',
    'SMTP' => $vendorDir . '/phpmailer/phpmailer/class.smtp.php',
    'SessionHandlerInterface' => $vendorDir . '/symfony/http-foundation/Symfony/Component/HttpFoundation/Resources/stubs/SessionHandlerInterface.php',
    'Symfony\\Component\\HttpFoundation\\Resources\\stubs\\FakeFile' => $vendorDir . '/symfony/http-foundation/Symfony/Component/HttpFoundation/Resources/stubs/FakeFile.php',
    'WmfFramework_Drupal' => $vendorDir . '/wikimedia/donation-interface/gateway_common/WmfFramework.drupal.php',
    'WmfFramework_Mediawiki' => $vendorDir . '/wikimedia/donation-interface/gateway_common/WmfFramework.mediawiki.php',
    'WorldPayAdapter' => $vendorDir . '/wikimedia/donation-interface/worldpay_gateway/worldpay.adapter.php',
    'WorldPayGateway' => $vendorDir . '/wikimedia/donation-interface/worldpay_gateway/worldpay_gateway.body.php',
    'WorldPayValidateApi' => $vendorDir . '/wikimedia/donation-interface/worldpay_gateway/worldpay.api.php',
    'phpmailerException' => $vendorDir . '/phpmailer/phpmailer/class.phpmailer.php',
);
