<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit713b445f683293f4a04a72f73555246e
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        'e40631d46120a9c38ea139981f8dab26' => __DIR__ . '/..' . '/ircmaxell/password-compat/lib/password.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/bootstrap.php',
        'edc6464955a37aa4d5fbf39d40fb6ee7' => __DIR__ . '/..' . '/symfony/polyfill-php55/bootstrap.php',
        '5255c38a0faeba867671b61dfda6d864' => __DIR__ . '/..' . '/paragonie/random_compat/lib/random.php',
        'bf34263f834e2781b79cae4d55a1d350' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/WmfFramework.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib\\' => 10,
        ),
        'W' => 
        array (
            'Wikimedia\\Composer\\' => 19,
        ),
        'T' => 
        array (
            'Twig\\' => 5,
        ),
        'S' => 
        array (
            'Symfony\\Polyfill\\Php55\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\Yaml\\' => 23,
            'Symfony\\Component\\HttpFoundation\\' => 33,
            'Symfony\\Component\\EventDispatcher\\' => 34,
            'Statistics\\' => 11,
            'SmashPig\\' => 9,
            'SilverpopConnector\\' => 19,
            'Samples\\' => 8,
        ),
        'R' => 
        array (
            'Respect\\Validation\\' => 19,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Cache\\' => 10,
            'Predis\\' => 7,
            'PayWithAmazon\\' => 14,
        ),
        'O' => 
        array (
            'Omnimail\\Silverpop\\' => 19,
            'Omnimail\\' => 9,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
            'MaxMind\\WebService\\' => 19,
            'MaxMind\\Exception\\' => 18,
            'MaxMind\\Db\\' => 11,
            'MaxMind\\' => 8,
        ),
        'L' => 
        array (
            'League\\Csv\\' => 11,
        ),
        'H' => 
        array (
            'Http\\Promise\\' => 13,
            'Http\\Client\\' => 12,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
            'GetOptionKit\\' => 13,
            'GeoIp2\\' => 7,
        ),
        'C' => 
        array (
            'Composer\\CaBundle\\' => 18,
        ),
        'A' => 
        array (
            'Addshore\\Psr\\Cache\\MWBagOStuffAdapter\\' => 38,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
        ),
        'Wikimedia\\Composer\\' => 
        array (
            0 => __DIR__ . '/..' . '/wikimedia/composer-merge-plugin/src',
        ),
        'Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
        'Symfony\\Polyfill\\Php55\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php55',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'Symfony\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'Statistics\\' => 
        array (
            0 => __DIR__ . '/..' . '/jackgleeson/stats-collector/src',
        ),
        'SmashPig\\' => 
        array (
            0 => __DIR__ . '/..' . '/wikimedia/smash-pig',
        ),
        'SilverpopConnector\\' => 
        array (
            0 => __DIR__ . '/..' . '/mrmarkfrench/silverpop-php-connector/src/SilverpopConnector',
        ),
        'Samples\\' => 
        array (
            0 => __DIR__ . '/..' . '/jackgleeson/stats-collector/samples',
        ),
        'Respect\\Validation\\' => 
        array (
            0 => __DIR__ . '/..' . '/respect/validation/library',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Predis\\' => 
        array (
            0 => __DIR__ . '/..' . '/predis/predis/src',
        ),
        'PayWithAmazon\\' => 
        array (
            0 => __DIR__ . '/..' . '/amzn/login-and-pay-with-amazon-sdk-php/PayWithAmazon',
        ),
        'Omnimail\\Silverpop\\' => 
        array (
            0 => __DIR__ . '/../..' . '/sites/default/civicrm/extensions/org.wikimedia.omnimail/src',
            1 => __DIR__ . '/..' . '/wikimedia/omnimail-silverpop/src',
        ),
        'Omnimail\\' => 
        array (
            0 => __DIR__ . '/..' . '/omnimail/omnimail/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'MaxMind\\WebService\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind/web-service-common/src/WebService',
        ),
        'MaxMind\\Exception\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind/web-service-common/src/Exception',
        ),
        'MaxMind\\Db\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind-db/reader/src/MaxMind/Db',
        ),
        'MaxMind\\' => 
        array (
            0 => __DIR__ . '/..' . '/maxmind/minfraud/src',
        ),
        'League\\Csv\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/csv/src',
        ),
        'Http\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-http/promise/src',
        ),
        'Http\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/php-http/httplug/src',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'GetOptionKit\\' => 
        array (
            0 => __DIR__ . '/..' . '/corneltek/getoptionkit/src',
        ),
        'GeoIp2\\' => 
        array (
            0 => __DIR__ . '/..' . '/geoip2/geoip2/src',
        ),
        'Composer\\CaBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/ca-bundle/src',
        ),
        'Addshore\\Psr\\Cache\\MWBagOStuffAdapter\\' => 
        array (
            0 => __DIR__ . '/..' . '/addshore/psr-6-mediawiki-bagostuff-adapter/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'c' => 
        array (
            'cogpowered\\FineDiff' => 
            array (
                0 => __DIR__ . '/..' . '/cogpowered/finediff/src',
            ),
        ),
        'T' => 
        array (
            'Twig_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
        'P' => 
        array (
            'PHPQueue' => 
            array (
                0 => __DIR__ . '/..' . '/coderkungfu/php-queue/src',
            ),
        ),
        'F' => 
        array (
            'ForceUTF8\\' => 
            array (
                0 => __DIR__ . '/..' . '/neitanod/forceutf8/src',
            ),
        ),
        'D' => 
        array (
            'Dflydev\\DotAccessData' => 
            array (
                0 => __DIR__ . '/..' . '/dflydev/dot-access-data/src',
            ),
        ),
        'C' => 
        array (
            'Clio' => 
            array (
                0 => __DIR__ . '/..' . '/clio/clio/src',
            ),
        ),
    );

    public static $classMap = array (
        'AdyenAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/adyen.adapter.php',
        'AdyenGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/adyen_gateway.body.php',
        'AdyenGatewayResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/adyen_resultswitcher.body.php',
        'AdyenHostedSignature' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/AdyenHostedSignature.php',
        'AmazonAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/amazon_gateway/amazon.adapter.php',
        'AmazonBillingApi' => __DIR__ . '/..' . '/wikimedia/donation-interface/amazon_gateway/amazon.api.php',
        'AmazonGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/amazon_gateway/amazon_gateway.body.php',
        'Amount' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/Amount.php',
        'AmountInCents' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/AmountInCents.php',
        'AmountInMinorUnits' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/AmountInMinorUnits.php',
        'ArrayHelper' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ArrayHelper.php',
        'AstroPayAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/astropay_gateway/astropay.adapter.php',
        'AstroPayFinancialNumbers' => __DIR__ . '/..' . '/wikimedia/donation-interface/astropay_gateway/AstroPayFinancialNumbers.php',
        'AstroPayGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/astropay_gateway/astropay_gateway.body.php',
        'AstroPayGatewayResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/astropay_gateway/astropay_resultswitcher.body.php',
        'AstroPayMethodCodec' => __DIR__ . '/..' . '/wikimedia/donation-interface/astropay_gateway/AstroPayMethodCodec.php',
        'AstroPaySignature' => __DIR__ . '/..' . '/wikimedia/donation-interface/astropay_gateway/AstroPaySignature.php',
        'AstroPayStatusQuery' => __DIR__ . '/..' . '/wikimedia/donation-interface/astropay_gateway/scripts/status.php',
        'BannerHistoryLogIdProcessor' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/banner_history/BannerHistoryLogIdProcessor.php',
        'BlankAddressFields' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/BlankAddressFields.php',
        'CleanupRecurringLength' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/CleanupRecurringLength.php',
        'ClientErrorApi' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/clientError.api.php',
        'ClientSideValidationHelper' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ClientSideValidationHelper.php',
        'ConfigurationReader' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ConfigurationReader.php',
        'ContributionTrackingPlusUnique' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ContributionTrackingPlusUnique.php',
        'CountryValidation' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/CountryValidation.php',
        'DataValidator' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DataValidator.php',
        'DonationApi' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/donation.api.php',
        'DonationData' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonationData.php',
        'DonationInterface' => __DIR__ . '/..' . '/wikimedia/donation-interface/DonationInterface.class.php',
        'DonationLogProcessor' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonationLogProcessor.php',
        'DonationLoggerFactory' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonationLoggerFactory.php',
        'DonationProfiler' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonationProfiler.php',
        'DonorEmail' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonorEmail.php',
        'DonorFullName' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonorFullName.php',
        'DonorLanguage' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonorLanguage.php',
        'DonorLocale' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonorLocale.php',
        'DummyFiscalNumber' => __DIR__ . '/..' . '/wikimedia/donation-interface/astropay_gateway/DummyFiscalNumber.php',
        'EasyPeasyICS' => __DIR__ . '/..' . '/phpmailer/phpmailer/extras/EasyPeasyICS.php',
        'EncodingMangler' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/EncodingMangler.php',
        'ErrorState' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ErrorState.php',
        'FallbackLogPrefixer' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/FallbackLogPrefixer.php',
        'FinalStatus' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/FinalStatus.php',
        'FiscalNumber' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/FiscalNumber.php',
        'FraudFilter' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/FraudFilter.php',
        'FullNameWithExceptions' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/FullNameWithExceptions.php',
        'GatewayAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/gateway.adapter.php',
        'GatewayPage' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/GatewayPage.php',
        'GatewayType' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/GatewayType.php',
        'Gateway_Extras' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/extras.body.php',
        'Gateway_Extras_ConversionLog' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/conversion_log/conversion_log.body.php',
        'Gateway_Extras_CustomFilters' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/custom_filters/custom_filters.body.php',
        'Gateway_Extras_CustomFilters_Functions' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/custom_filters/filters/functions/functions.body.php',
        'Gateway_Extras_CustomFilters_IP_Velocity' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/custom_filters/filters/ip_velocity/ip_velocity.body.php',
        'Gateway_Extras_CustomFilters_MinFraud' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/custom_filters/filters/minfraud/minfraud.body.php',
        'Gateway_Extras_CustomFilters_Referrer' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/custom_filters/filters/referrer/referrer.body.php',
        'Gateway_Extras_CustomFilters_Source' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/custom_filters/filters/source/source.body.php',
        'Gateway_Extras_SessionVelocityFilter' => __DIR__ . '/..' . '/wikimedia/donation-interface/extras/session_velocity/session_velocity.body.php',
        'Gateway_Form' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_forms/Form.php',
        'Gateway_Form_Mustache' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_forms/Mustache.php',
        'GlobalCollectAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/globalcollect.adapter.php',
        'GlobalCollectGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/globalcollect_gateway.body.php',
        'GlobalCollectGatewayResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/globalcollect_resultswitcher.body.php',
        'GlobalCollectGetDirectory' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/scripts/get_directory.php',
        'GlobalCollectOrphanAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/orphan.adapter.php',
        'GlobalCollectOrphanRectifier' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/GlobalCollectOrphanRectifier.php',
        'GlobalCollectRefundMaintenance' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/scripts/refund.php',
        'IngenicoFinancialNumber' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/IngenicoFinancialNumber.php',
        'IngenicoLanguage' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/IngenicoLanguage.php',
        'IngenicoMethodCodec' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/IngenicoMethodCodec.php',
        'IngenicoReturntoHelper' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/IngenicoReturntoHelper.php',
        'IsoDate' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/IsoDate.php',
        'LCRun3' => __DIR__ . '/..' . '/zordius/lightncandy/src/lightncandy.php',
        'LightnCandy' => __DIR__ . '/..' . '/zordius/lightncandy/src/lightncandy.php',
        'LocalClusterPsr6Cache' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/LocalClusterPsr6Cache.php',
        'LogPrefixProvider' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/LogPrefixProvider.php',
        'MessageUtils' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/MessageUtils.php',
        'MustacheErrorForm' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_forms/MustacheErrorForm.php',
        'PHPMailer' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
        'PHPMailerOAuth' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmaileroauth.php',
        'PHPMailerOAuthGoogle' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmaileroauthgoogle.php',
        'POP3' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.pop3.php',
        'PayPalCountry' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/PayPalCountry.php',
        'PaymentError' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/PaymentError.php',
        'PaymentMethod' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/PaymentMethod.php',
        'PaymentResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/PaymentResult.php',
        'PaymentTransactionResponse' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/PaymentTransactionResponse.php',
        'PaypalExpressAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/express_checkout/paypal_express.adapter.php',
        'PaypalExpressGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/express_checkout/paypal_express_gateway.body.php',
        'PaypalExpressGatewayResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/express_checkout/paypal_express_resultswitcher.body.php',
        'PaypalExpressReturnUrl' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/express_checkout/PaypalExpressReturnUrl.php',
        'PaypalLegacyAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/legacy/paypal_legacy.adapter.php',
        'PaypalLegacyGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/legacy/paypal_legacy_gateway.body.php',
        'PaypalLegacyLocale' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/legacy/PaypalLegacyLocale.php',
        'ResponseCodes' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ResponseCodes.php',
        'ResponseProcessingException' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ResponseProcessingException.php',
        'ResultPages' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ResultPages.php',
        'RiskScore' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/RiskScore.php',
        'SMTP' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.smtp.php',
        'StagingHelper' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/StagingHelper.php',
        'StreetAddress' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/StreetAddress.php',
        'Subdivisions' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_forms/includes/Subdivisions.php',
        'UnstagingHelper' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/UnstagingHelper.php',
        'ValidationError' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ValidationError.php',
        'ValidationHelper' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ValidationHelper.php',
        'WmfFrameworkLogHandler' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/WmfFrameworkLogHandler.php',
        'WmfFramework_Drupal' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/WmfFramework.drupal.php',
        'WmfFramework_Mediawiki' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/WmfFramework.mediawiki.php',
        'ntlm_sasl_client_class' => __DIR__ . '/..' . '/phpmailer/phpmailer/extras/ntlm_sasl_client.php',
        'phpmailerException' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit713b445f683293f4a04a72f73555246e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit713b445f683293f4a04a72f73555246e::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit713b445f683293f4a04a72f73555246e::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit713b445f683293f4a04a72f73555246e::$classMap;

        }, null, ClassLoader::class);
    }
}
