<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'cogpowered\\FineDiff' => array($vendorDir . '/cogpowered/finediff/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'System' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Net' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Math' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'FuseSource' => array($vendorDir . '/fusesource/stomp-php/src'),
    'File' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Crypt' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
);
