<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit713b445f683293f4a04a72f73555246e
{
    public static $files = array (
        '3919eeb97e98d4648304477f8ef734ba' => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib/Crypt/Random.php',
        'bf34263f834e2781b79cae4d55a1d350' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/WmfFramework.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Component\\Yaml\\' => 23,
            'SmashPig\\' => 9,
        ),
        'P' => 
        array (
            'Predis\\' => 7,
            'PayWithAmazon\\' => 14,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'SmashPig\\' => 
        array (
            0 => __DIR__ . '/..' . '/wikimedia/smash-pig',
        ),
        'Predis\\' => 
        array (
            0 => __DIR__ . '/..' . '/predis/predis/src',
        ),
        'PayWithAmazon\\' => 
        array (
            0 => __DIR__ . '/..' . '/amzn/login-and-pay-with-amazon-sdk-php/PayWithAmazon',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
    );

    public static $prefixesPsr0 = array (
        'c' => 
        array (
            'cogpowered\\FineDiff' => 
            array (
                0 => __DIR__ . '/..' . '/cogpowered/finediff/src',
            ),
        ),
        'T' => 
        array (
            'Twig_' => 
            array (
                0 => __DIR__ . '/..' . '/twig/twig/lib',
            ),
        ),
        'S' => 
        array (
            'System' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
            'Symfony\\Component\\HttpFoundation\\' => 
            array (
                0 => __DIR__ . '/..' . '/symfony/http-foundation',
            ),
            'Symfony\\Component\\EventDispatcher\\' => 
            array (
                0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
            ),
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 
            array (
                0 => __DIR__ . '/..' . '/psr/log',
            ),
            'PHPQueue' => 
            array (
                0 => __DIR__ . '/..' . '/coderkungfu/php-queue/src',
            ),
        ),
        'N' => 
        array (
            'Net' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
        ),
        'M' => 
        array (
            'Math' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
        ),
        'F' => 
        array (
            'FuseSource' => 
            array (
                0 => __DIR__ . '/..' . '/fusesource/stomp-php/src',
            ),
            'File' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
        ),
        'C' => 
        array (
            'Crypt' => 
            array (
                0 => __DIR__ . '/..' . '/phpseclib/phpseclib/phpseclib',
            ),
            'Clio' => 
            array (
                0 => __DIR__ . '/..' . '/clio/clio/src',
            ),
        ),
    );

    public static $classMap = array (
        'AdyenAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/adyen.adapter.php',
        'AdyenGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/adyen_gateway.body.php',
        'AdyenGatewayResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/adyen_gateway/adyen_resultswitcher.body.php',
        'AmazonAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/amazon_gateway/amazon.adapter.php',
        'AmazonBillingApi' => __DIR__ . '/..' . '/wikimedia/donation-interface/amazon_gateway/amazon.api.php',
        'AmazonGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/amazon_gateway/amazon_gateway.body.php',
        'CurrencyRates' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/CurrencyRates.php',
        'CyclicalArray' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/CyclicalArray.php',
        'DataValidator' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DataValidator.php',
        'DonationApi' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/donation.api.php',
        'DonationData' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonationData.php',
        'DonationLogProcessor' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonationLogProcessor.php',
        'DonationLoggerFactory' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonationLoggerFactory.php',
        'DonationQueue' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/DonationQueue.php',
        'EncodingMangler' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/EncodingMangler.php',
        'FinalStatus' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/FinalStatus.php',
        'GatewayAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/gateway.adapter.php',
        'GatewayPage' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/GatewayPage.php',
        'GatewayType' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/gateway.adapter.php',
        'GlobalCollectAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/globalcollect.adapter.php',
        'GlobalCollectGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/globalcollect_gateway.body.php',
        'GlobalCollectGatewayResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/globalcollect_resultswitcher.body.php',
        'GlobalCollectOrphanAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/orphan.adapter.php',
        'GlobalCollectOrphanRectifier' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/GlobalCollectOrphanRectifier.php',
        'GlobalCollectRefundMaintenance' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/scripts/refund.php',
        'LCRun3' => __DIR__ . '/..' . '/zordius/lightncandy/src/lightncandy.php',
        'LightnCandy' => __DIR__ . '/..' . '/zordius/lightncandy/src/lightncandy.php',
        'LogPrefixProvider' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/gateway.adapter.php',
        'MessageUtils' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/MessageUtils.php',
        'NationalCurrencies' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/NationalCurrencies.php',
        'OrphanMaintenance' => __DIR__ . '/..' . '/wikimedia/donation-interface/globalcollect_gateway/scripts/orphans.php',
        'PHPMailer' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
        'POP3' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.pop3.php',
        'PaymentMethod' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/PaymentMethod.php',
        'PaymentResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/PaymentResult.php',
        'PaymentTransactionResponse' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/PaymentTransactionResponse.php',
        'PaypalAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/paypal.adapter.php',
        'PaypalGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/paypal_gateway.body.php',
        'PaypalGatewayResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/paypal_gateway/paypal_resultswitcher.body.php',
        'ResponseCodes' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ResponseCodes.php',
        'ResponseProcessingException' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/ResponseProcessingException.php',
        'SMTP' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.smtp.php',
        'SessionHandlerInterface' => __DIR__ . '/..' . '/symfony/http-foundation/Symfony/Component/HttpFoundation/Resources/stubs/SessionHandlerInterface.php',
        'Symfony\\Component\\HttpFoundation\\Resources\\stubs\\FakeFile' => __DIR__ . '/..' . '/symfony/http-foundation/Symfony/Component/HttpFoundation/Resources/stubs/FakeFile.php',
        'WmfFrameworkLogHandler' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/WmfFrameworkLogHandler.php',
        'WmfFramework_Drupal' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/WmfFramework.drupal.php',
        'WmfFramework_Mediawiki' => __DIR__ . '/..' . '/wikimedia/donation-interface/gateway_common/WmfFramework.mediawiki.php',
        'WorldpayAdapter' => __DIR__ . '/..' . '/wikimedia/donation-interface/worldpay_gateway/worldpay.adapter.php',
        'WorldpayGateway' => __DIR__ . '/..' . '/wikimedia/donation-interface/worldpay_gateway/worldpay_gateway.body.php',
        'WorldpayGatewayResult' => __DIR__ . '/..' . '/wikimedia/donation-interface/worldpay_gateway/worldpay_resultswitcher.body.php',
        'WorldpayValidateApi' => __DIR__ . '/..' . '/wikimedia/donation-interface/worldpay_gateway/worldpay.api.php',
        'phpmailerException' => __DIR__ . '/..' . '/phpmailer/phpmailer/class.phpmailer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit713b445f683293f4a04a72f73555246e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit713b445f683293f4a04a72f73555246e::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit713b445f683293f4a04a72f73555246e::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit713b445f683293f4a04a72f73555246e::$classMap;

        }, null, ClassLoader::class);
    }
}
