<?php

// include_paths.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/pear/auth_sasl',
    $vendorDir . '/pear/console_getopt',
    $vendorDir . '/pear/log',
    $vendorDir . '/pear/mail',
    $vendorDir . '/pear/mail_mime',
    $vendorDir . '/pear/net_smtp',
    $vendorDir . '/pear/net_socket',
    $vendorDir . '/pear/pear-core-minimal/src',
    $vendorDir . '/pear/pear_exception',
    $vendorDir . '/pear/validate_finance_creditcard',
    $vendorDir . '/pear/db',
);
