<?php return array(
    'root' => array(
        'name' => 'wikimedia/fundraising-crm',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '72ecb3c9497078e4fc457878c716039877024d39',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'adrienrn/php-mimetyper' => array(
            'pretty_version' => '0.2.2',
            'version' => '0.2.2.0',
            'reference' => '702e00a604b4baed34d69730ce055e05c0f43932',
            'type' => 'library',
            'install_path' => __DIR__ . '/../adrienrn/php-mimetyper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'behat/mink' => array(
            'pretty_version' => 'v1.13.0',
            'version' => '1.13.0.0',
            'reference' => '9b08f62937c173affe070c04bb072d7ea1db1be5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/mink',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.14.8',
            'version' => '0.14.8.0',
            'reference' => '63422359a44b7f06cae63c3b429b59e8efcc0629',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'brick/money' => array(
            'pretty_version' => '0.10.3',
            'version' => '0.10.3.0',
            'reference' => 'b1b0bb6035d26a58f29b1c06b1265c01a0b5c9c3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/money',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'civicrm/composer-compile-lib' => array(
            'pretty_version' => 'v0.9',
            'version' => '0.9.0.0',
            'reference' => '6d96a49f50c4ab2e52d0f549272e7861a61d5ad0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../civicrm/composer-compile-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'civicrm/composer-compile-plugin' => array(
            'pretty_version' => 'v0.22',
            'version' => '0.22.0.0',
            'reference' => '608f4d69d88f9759f33d2f237381c485f9649ea0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../civicrm/composer-compile-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'civicrm/composer-downloads-plugin' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => '7af08ca4a78607ac2bad3215c05a10390da9c673',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../civicrm/composer-downloads-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'civicrm/gitignore' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '7491782ee89c4e14bbcc9b30bebb90389054cb2e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../civicrm/gitignore',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'clio/clio' => array(
            'pretty_version' => '0.1.8',
            'version' => '0.1.8.0',
            'reference' => '6a9f600b73fa213e817d5c1e67a4641aecd156ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clio/clio',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'clue/stream-filter' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'reference' => '049509fef80032cb3f051595029ab75b49a3c2f7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clue/stream-filter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'coderkungfu/php-queue' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => '773763fe78d1193cc890735d4892a8dfa5fe6f8f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../coderkungfu/php-queue',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.4.0',
            'version' => '3.4.0.0',
            'reference' => 'd5a341b3fb61f3001970940afb1d332968a183ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'corneltek/getoptionkit' => array(
            'pretty_version' => '2.7.3',
            'version' => '2.7.3.0',
            'reference' => '3d42c14251cfd8becbffc851852de3587d4e8eec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../corneltek/getoptionkit',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cweagans/composer-patches' => array(
            'pretty_version' => '1.7.3',
            'version' => '1.7.3.0',
            'reference' => 'e190d4466fe2b103a55467dfa83fc2fecfcaf2db',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../cweagans/composer-patches',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dflydev/apache-mime-types' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'f30a57e59b7476e4c5270b6a0727d79c9c0eb861',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/apache-mime-types',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dflydev/dot-access-data' => array(
            'pretty_version' => 'v3.0.3',
            'version' => '3.0.3.0',
            'reference' => 'a23a2bf4f31d3518f3ecb38660c95715dfead60f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-data',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dmore/chrome-mink-driver' => array(
            'pretty_version' => '2.10.0',
            'version' => '2.10.0.0',
            'reference' => '197c3a2e69a0d9f2572ca4461e748d0c771db4ec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dmore/chrome-mink-driver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '31ad66abc0fc9e1a1f2d9bc6a42668d2fbbcd6dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v3.1.5',
            'version' => '3.1.5.0',
            'reference' => 'f11ead23a8a76d0ff9bbc6c7c8fd7e05ca328496',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dompdf/php-font-lib' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'a6e9a688a2a80016ac080b97be73d3e10c444c9a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/php-font-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dompdf/php-svg-lib' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '8259ffb930817e72b1ff1caef5d226501f3dfeb1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/php-svg-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => 'd42c8731f0624ad6bdc8d3e5e9a4524f68801cfa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.19.0',
            'version' => '4.19.0.0',
            'reference' => 'b287d2a16aceffbf6e0295559b39662612b77fcf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v7.1.0',
            'version' => '7.1.0.0',
            'reference' => 'b374a5d1a4f1f67fadc2165cdb284645945e2fc0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geo6/geocoder-php-addok-provider' => array(
            'pretty_version' => 'v1.6.0',
            'version' => '1.6.0.0',
            'reference' => 'ea471a2bfa9c55cfbf077684b5aa58568be2ad5b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geo6/geocoder-php-addok-provider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geocoder-php/common-http' => array(
            'pretty_version' => '4.7.0',
            'version' => '4.7.0.0',
            'reference' => '4209be6c31946ed5a658f6240ab21faaf5413f61',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/common-http',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geocoder-php/free-geoip-provider' => array(
            'pretty_version' => '4.6.0',
            'version' => '4.6.0.0',
            'reference' => '5181a785f08948ee651aa759d7cb93fa60776b91',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/free-geoip-provider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geocoder-php/google-maps-provider' => array(
            'pretty_version' => '4.8.0',
            'version' => '4.8.0.0',
            'reference' => '587aac3647ebd2ce2090b613fc56c753b9dee9a7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/google-maps-provider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geocoder-php/here-provider' => array(
            'pretty_version' => '0.8.0',
            'version' => '0.8.0.0',
            'reference' => 'a5801903fd0ea9a29fd3ba7273dd6e38e275d13c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/here-provider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geocoder-php/mapquest-provider' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'reference' => '7d563294dfe1f68d847b08e9c17a13138e2a31ed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/mapquest-provider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geocoder-php/nominatim-provider' => array(
            'pretty_version' => '5.8.0',
            'version' => '5.8.0.0',
            'reference' => '1b6852d33e9b558a13d98510fff66e76f4aed9b2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/nominatim-provider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'geocoder-php/provider-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'gr4vy/gr4vy-php' => array(
            'pretty_version' => 'v0.27.0',
            'version' => '0.27.0.0',
            'reference' => 'e0e3da9b4d20e0dac1cc8448fb60fce858bc0fa7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gr4vy/gr4vy-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.12.1',
            'version' => '7.12.1.0',
            'reference' => 'd34627490fbc03bf5c5d7cfed81f2faa19519425',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => '4360e982f87f5f258bf872d094647791db2f4c8e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.12.1',
            'version' => '2.12.1.0',
            'reference' => '172ef2f4e9824c1e058b7f30be8ae25a02c0f2b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'henrikbjorn/lurker' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'jackgleeson/stats-collector' => array(
            'pretty_version' => 'v1.5.0',
            'version' => '1.5.0.0',
            'reference' => '5955ea4830986dac1d157ebd7dcae58f0436245a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jackgleeson/stats-collector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'knplabs/knp-snappy' => array(
            'pretty_version' => 'v1.7.2',
            'version' => '1.7.2.0',
            'reference' => '1461239a8b265fcc5457b7bdeb842c75b0f066eb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../knplabs/knp-snappy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/serializable-closure' => array(
            'pretty_version' => 'v1.3.7',
            'version' => '1.3.7.0',
            'reference' => '4f48ade902b94323ca3be7646db16209ec76be3d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/serializable-closure',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lcobucci/clock' => array(
            'pretty_version' => '3.3.1',
            'version' => '3.3.1.0',
            'reference' => 'db3713a61addfffd615b79bf0bc22f0ccc61b86b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lcobucci/jwt' => array(
            'pretty_version' => '4.3.0',
            'version' => '4.3.0.0',
            'reference' => '4d7de2fe0d51a96418c0d04004986e410e87f6b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/csv' => array(
            'pretty_version' => '9.28.0',
            'version' => '9.28.0.0',
            'reference' => '6582ace29ae09ba5b07049d40ea13eb19c8b5073',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/csv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/oauth2-client' => array(
            'pretty_version' => '2.9.0',
            'version' => '2.9.0.0',
            'reference' => '26e8c5da4f3d78cede7021e09b1330a0fc093d5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/oauth2-google' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => '72be69505f890ea8b6d4e716f619b3c10a1f5010',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/oauth2-google',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '3.1.2',
            'version' => '3.1.2.0',
            'reference' => 'aeadcf5c412332eb426c0f9b4485f6accba2a99f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'marcj/topsort' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '387086c2db60ee0a27ac5df588c0f0b30c6bdc4b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../marcj/topsort',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '728434227fe21be27ff6d86621a1b13107a2562c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.10.0',
            'version' => '2.10.0.0',
            'reference' => 'fcf91eb64359852f00d921887b219479b4f21251',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.11.0',
            'version' => '2.11.0.0',
            'reference' => '37308608e599f34a1a4845b16440047ec98a172a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mrmarkfrench/silverpop-php-connector' => array(
            'pretty_version' => '1.6.12',
            'version' => '1.6.12.0',
            'reference' => '84fe4e802d4e4510a0df11e3f70d7eeaeaecc215',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mrmarkfrench/silverpop-php-connector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'omnimail/omnimail' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '9b5434d1330d54bdcfe5597f9c3cc227f56b1b4f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../omnimail/omnimail',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'padaliyajay/php-autoprefixer' => array(
            'pretty_version' => '1.5',
            'version' => '1.5.0.0',
            'reference' => '0fe905f63ba87c130eb712b69eb81a660c8127c6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../padaliyajay/php-autoprefixer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/constant_time_encoding' => array(
            'pretty_version' => 'v3.1.3',
            'version' => '3.1.3.0',
            'reference' => 'd5b01a39b3415c2cd581d3bd3a3575c1ebbd8e77',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/constant_time_encoding',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/auth_sasl' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => 'ebf4c2c5ea190b283229f8443b866ccf34422471',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/auth_sasl',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/db' => array(
            'pretty_version' => 'v1.12.3',
            'version' => '1.12.3.0',
            'reference' => '97ea56201976c58dfbc5825fd3aaef484aab53c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/db',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/log' => array(
            'pretty_version' => '1.14.5',
            'version' => '1.14.5.0',
            'reference' => '38e6668ead984d446161acc1ba257cf77ec67bcd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'eb053f8b74f4f3178105fcf001626e63068c0dbc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/mail_mime' => array(
            'pretty_version' => '1.10.12',
            'version' => '1.10.12.0',
            'reference' => 'd032c7c9335e96d5954ac6e93d33955f3b7246e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/mail_mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_smtp' => array(
            'pretty_version' => '1.12.2',
            'version' => '1.12.2.0',
            'reference' => '76173b3ee542a683127ab5429612b6ea519db64d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_smtp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_socket' => array(
            'pretty_version' => 'v1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'f31d75ac352d49908f8987bbb1496c02a409812a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_socket',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.18',
            'version' => '1.10.18.0',
            'reference' => 'c7b55789d01de0ce090d289b73f1bbd6a2f113b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/validate_finance_creditcard' => array(
            'pretty_version' => '0.7.0',
            'version' => '0.7.0.0',
            'reference' => 'f138fb80b2305c1fe7ca33216b895b868396f1e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/validate_finance_creditcard',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phlib/xss-sanitizer' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '09f6ebff966f8318ea41015eb7f1dc786e7e2b7f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phlib/xss-sanitizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/discovery' => array(
            'pretty_version' => '1.20.0',
            'version' => '1.20.0.0',
            'reference' => '82fe4c73ef3363caed49ff8dd1539ba06044910d',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../php-http/discovery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/httplug' => array(
            'pretty_version' => '2.4.1',
            'version' => '2.4.1.0',
            'reference' => '5cad731844891a4c282f3f3e1b582c46839d22f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/httplug',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/message' => array(
            'pretty_version' => '1.16.2',
            'version' => '1.16.2.0',
            'reference' => '06dd5e8562f84e641bf929bfe699ee0f5ce8080a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-http/message-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/promise' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => 'fc85b1fba37c169a69a07ef0d5a8075770cc1f83',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/promise',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.12.0',
            'version' => '6.12.0.0',
            'reference' => 'd1ac35d784bf9f5e61b424901d5a014967f15b12',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/math' => array(
            'pretty_version' => '0.3.0',
            'version' => '0.3.0.0',
            'reference' => 'fc31c8f57a7a81f962cbf389fd89f4d9d06fc99a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '5.8.0',
            'version' => '5.8.0.0',
            'reference' => '01964d92536edf1a3a874b9580a52824bebf6fbb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpword' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => '6d75328229bc93790b37e93741adf70646cea958',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpword',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '3.0.55',
            'version' => '3.0.55.0',
            'reference' => 'db9744e6d47e742b1f974e965ad49bdd041105af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0.55',
            ),
        ),
        'phpseclib/phpseclib2_compat' => array(
            'pretty_version' => '1.0.10',
            'version' => '1.0.10.0',
            'reference' => 'ea9bab88011a4facf89b39a9d62d58fb8fd9b1b3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib2_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phrity/net-stream' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '9105931b65ad90c75f4885a40b268b0f65802e3e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phrity/net-stream',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phrity/net-uri' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '3f458e0c4d1ddc0e218d7a5b9420127c63925f43',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phrity/net-uri',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phrity/util-errorhandler' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '70a669cc22db2eed6a109ec66fd95168a4332c9b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phrity/util-errorhandler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phrity/websocket' => array(
            'pretty_version' => '1.7.3',
            'version' => '1.7.3.0',
            'reference' => '8a525da4457b599ab1960f24183f25626c96ce3c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phrity/websocket',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pontedilana/php-weasyprint' => array(
            'pretty_version' => '2.7.0',
            'version' => '2.7.0.0',
            'reference' => 'eaadec8389ce3e3d43f1fe6bbca415c06262a262',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pontedilana/php-weasyprint',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'predis/predis' => array(
            'pretty_version' => 'v3.5.1',
            'version' => '3.5.1.0',
            'reference' => '5c996db191ee2d9bafe651f454b1fca16754271b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../predis/predis',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/clock' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'e41a24703d4560fd0acb709162f73b8adfc3aa0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/clock-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
                1 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
                1 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
                1 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0 || 2.0.0 || 3.0.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.18',
            ),
        ),
        'rubobaquero/phpquery' => array(
            'pretty_version' => '0.9.15',
            'version' => '0.9.15.0',
            'reference' => 'd2c3c1bb8a9d48dd0f1230bda2413ce38108b5fe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../rubobaquero/phpquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => 'v9.4.0',
            'version' => '9.4.0.0',
            'reference' => 'fd3bf9fb173e0df649bc4e3e0d088a1b2417c08f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'scssphp/scssphp' => array(
            'pretty_version' => 'v1.13.0',
            'version' => '1.13.0.0',
            'reference' => '63d1157457e5554edf00b0c1fabab4c1511d2520',
            'type' => 'library',
            'install_path' => __DIR__ . '/../scssphp/scssphp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sgoettsch/monolog-rotating-file-handler' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '913e1de21981b252854e319549b5e1c450f5f22f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sgoettsch/monolog-rotating-file-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'soundasleep/html2text' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '83502b6f8f1aaef8e2e238897199d64f284b4af3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../soundasleep/html2text',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v7.4.10',
            'version' => '7.4.10.0',
            'reference' => 'd91b6c7cd2a8c9a9c2b8d26c8f5ed48edf99ef57',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v7.4.9',
            'version' => '7.4.9.0',
            'reference' => 'b75663ed96cf4756e28e3105476f220f92886cc4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v7.4.13',
            'version' => '7.4.13.0',
            'reference' => 'f299e20ce983be6c0744952533c6dfeaaa1448e2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.7.0',
            'version' => '3.7.0.0',
            'reference' => '50f59d1f3ca46d41ac911f97a78626b6756af35b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v7.4.9',
            'version' => '7.4.9.0',
            'reference' => 'e4a2e29753c7801f7a8340e066cfa788f3bc8101',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v3.7.0',
            'version' => '3.7.0.0',
            'reference' => 'ccba7060602b7fed0b03c85bf025257f76d9ef32',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v7.4.11',
            'version' => '7.4.11.0',
            'reference' => 'd721ea61b4a5fba8c5b6e7c1feda19efea144b50',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v7.4.8',
            'version' => '7.4.8.0',
            'reference' => 'e0be088d22278583a82da281886e8c3592fbf149',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v6.4.41',
            'version' => '6.4.41.0',
            'reference' => '48d76c29a67a301e0f7779a512bf76417395ffef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mailer' => array(
            'pretty_version' => 'v7.4.12',
            'version' => '7.4.12.0',
            'reference' => '5cefb712a25f320579615ba9e1942abaeade7dff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v7.4.13',
            'version' => '7.4.13.0',
            'reference' => 'a845722765c4f6b2ce88beaf4f4479975b186770',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.37.0',
            'version' => '1.37.0.0',
            'reference' => '141046a8f9477948ff284fa65be2095baafb94f2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.37.0',
            'version' => '1.37.0.0',
            'reference' => '2c5729fd241b4b22f6e4b436bc3354a4f262df57',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.38.1',
            'version' => '1.38.1.0',
            'reference' => 'dc21118016c039a66235cf93d96b435ffb282412',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.38.0',
            'version' => '1.38.0.0',
            'reference' => '2d446c214bdbe5b71bde5011b060a05fece3ae6b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.38.2',
            'version' => '1.38.2.0',
            'reference' => 'd3d318bad5e7a1bfbd026009c8bfb8d8f99ae6b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php54' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php55' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.37.0',
            'version' => '1.37.0.0',
            'reference' => 'dfb55726c3a76ea3b6459fcfda1ec2d80a682411',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php82' => array(
            'pretty_version' => 'v1.38.1',
            'version' => '1.38.1.0',
            'reference' => '002dc0cfe5fd4ed6033d48f27d4f19a486c4b04b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php82',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'v1.38.2',
            'version' => '1.38.2.0',
            'reference' => '796a26abb75ce49f3a84433cd81bf1009d73d5f8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php84' => array(
            'pretty_version' => 'v1.38.1',
            'version' => '1.38.1.0',
            'reference' => 'f4e1dfaee5b74aba5964fe1fd4dfc7ba5e3085fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php84',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php85' => array(
            'pretty_version' => 'v1.38.1',
            'version' => '1.38.1.0',
            'reference' => 'ba2ba04f3352cfa2dcbbcb90aee13ed967f505b1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php85',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v7.4.13',
            'version' => '7.4.13.0',
            'reference' => 'f5804be144caceb570f6747519999636b664f24c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.7.0',
            'version' => '3.7.0.0',
            'reference' => 'd25d82433a80eba6aa0e6c24b61d7370d99e444a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v7.4.8',
            'version' => '7.4.8.0',
            'reference' => '9510c3966f749a1d1ff0059e1eabef6cc621e7fd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v7.4.9',
            'version' => '7.4.9.0',
            'reference' => '22e03a49c95ef054a43601cd159b222bfab1c701',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v7.4.13',
            'version' => '7.4.13.0',
            'reference' => 'a7ec3b1156faf8815db7683ec7c1e7338e6f977c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tecnickcom/tcpdf' => array(
            'pretty_version' => '6.11.3',
            'version' => '6.11.3.0',
            'reference' => 'b18f6119161019916c5bb07cb8da5205ae5c1b63',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tcpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'thecodingmachine/safe' => array(
            'pretty_version' => 'v3.4.0',
            'version' => '3.4.0.0',
            'reference' => '705683a25bacf0d4860c7dea4d7947bfd09eea19',
            'type' => 'library',
            'install_path' => __DIR__ . '/../thecodingmachine/safe',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theiconic/name-parser' => array(
            'pretty_version' => 'v1.2.11',
            'version' => '1.2.11.0',
            'reference' => '9a54a713bf5b2e7fd990828147d42de16bf8a253',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theiconic/name-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'togos/gitignore' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '1.*',
            ),
        ),
        'totten/ca-config' => array(
            'pretty_version' => 'v23.07.0',
            'version' => '23.07.0.0',
            'reference' => '12571f07b994d555bf1a956e310f224da3ebbd8d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../totten/ca-config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'totten/lurkerlite' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'a20c47142b486415b9117c76aa4c2117ff95b49a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../totten/lurkerlite',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tplaner/when' => array(
            'pretty_version' => 'v3.2.1',
            'version' => '3.2.1.0',
            'reference' => 'f48a8a16c59cc629c8f474cbb6fdddae551385cd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tplaner/when',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tubalmartin/cssmin' => array(
            'pretty_version' => 'v4.1.1',
            'version' => '4.1.1.0',
            'reference' => '3cbf557f4079d83a06f9c3ff9b957c022d7805cf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tubalmartin/cssmin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'typo3/phar-stream-wrapper' => array(
            'pretty_version' => 'v4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'ce4b6e9873d4dd7dce2a397511713bf14977fdf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../typo3/phar-stream-wrapper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/civicrm-data-table-provider' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '7f1bf0a7ae5af3c8c9b4cbce03c25f4c69170391',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/civicrm-data-table-provider',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/composer-merge-plugin' => array(
            'pretty_version' => 'v2.1.0',
            'version' => '2.1.0.0',
            'reference' => 'a03d426c8e9fb2c9c569d9deeb31a083292788bc',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../wikimedia/composer-merge-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/fundraising-crm' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '72ecb3c9497078e4fc457878c716039877024d39',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/omnimail-silverpop' => array(
            'pretty_version' => '1.31',
            'version' => '1.31.0.0',
            'reference' => 'e928c3f9450ccb4d570a0a6b52c4bda0a7fe22e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/omnimail-silverpop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/smash-pig' => array(
            'pretty_version' => 'v1.2.4.13',
            'version' => '1.2.4.13',
            'reference' => 'f737652bdd10189434d45516b181ef1291b0b32c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/smash-pig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'willdurand/geocoder' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => 'a749e00819d2929bd0ec40fb79853956332970ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/geocoder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'xkerman/restricted-unserialize' => array(
            'pretty_version' => '1.1.12',
            'version' => '1.1.12.0',
            'reference' => '4c6cadbb176c04d3e19b9bb8b40df12998460489',
            'type' => 'library',
            'install_path' => __DIR__ . '/../xkerman/restricted-unserialize',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zetacomponents/base' => array(
            'pretty_version' => '1.9.5',
            'version' => '1.9.5.0',
            'reference' => 'f91dd2f04280741de7125350a8c47b6673fc8537',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zetacomponents/base',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'zetacomponents/mail' => array(
            'pretty_version' => '1.9.7',
            'version' => '1.9.7.0',
            'reference' => '1ba2285540771646fa7c3c881e8b6f97663a6d4a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../zetacomponents/mail',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
