<?php return array(
    'root' => array(
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => 'f3dd3921b274fff1b22a8e73d433c7a9b2bf9e63',
        'name' => 'wikimedia/fundraising-crm',
        'dev' => false,
    ),
    'versions' => array(
        'addshore/psr-6-mediawiki-bagostuff-adapter' => array(
            'pretty_version' => '0.1',
            'version' => '0.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../addshore/psr-6-mediawiki-bagostuff-adapter',
            'aliases' => array(),
            'reference' => '92f3bb69bf3e7f51b8b66ae74b6a4a291637354c',
            'dev_requirement' => false,
        ),
        'amzn/login-and-pay-with-amazon-sdk-php' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amzn/login-and-pay-with-amazon-sdk-php',
            'aliases' => array(),
            'reference' => '0c923fe9926621bb8a39a22cecd1d2f33c75de30',
            'dev_requirement' => false,
        ),
        'clio/clio' => array(
            'pretty_version' => '0.1.8',
            'version' => '0.1.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clio/clio',
            'aliases' => array(),
            'reference' => '6a9f600b73fa213e817d5c1e67a4641aecd156ef',
            'dev_requirement' => false,
        ),
        'clue/stream-filter' => array(
            'pretty_version' => 'v1.4.1',
            'version' => '1.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clue/stream-filter',
            'aliases' => array(),
            'reference' => '5a58cc30a8bd6a4eb8f856adf61dd3e013f53f71',
            'dev_requirement' => false,
        ),
        'coderkungfu/php-queue' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../coderkungfu/php-queue',
            'aliases' => array(),
            'reference' => 'cd29afd03a5b4b740ce6c50128f1e69723c54f72',
            'dev_requirement' => false,
        ),
        'cogpowered/finediff' => array(
            'pretty_version' => '0.3.1',
            'version' => '0.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cogpowered/finediff',
            'aliases' => array(),
            'reference' => '339ddc8c3afb656efed4f2f0a80e5c3d026f8ea8',
            'dev_requirement' => false,
        ),
        'composer/ca-bundle' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/./ca-bundle',
            'aliases' => array(),
            'reference' => 'd2c0a83b7533d6912e8d516756ebd34f893e9169',
            'dev_requirement' => false,
        ),
        'consolidation/annotated-command' => array(
            'pretty_version' => '2.12.0',
            'version' => '2.12.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/annotated-command',
            'aliases' => array(),
            'reference' => '512a2e54c98f3af377589de76c43b24652bcb789',
            'dev_requirement' => false,
        ),
        'consolidation/output-formatters' => array(
            'pretty_version' => '3.5.0',
            'version' => '3.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/output-formatters',
            'aliases' => array(),
            'reference' => '99ec998ffb697e0eada5aacf81feebfb13023605',
            'dev_requirement' => false,
        ),
        'corneltek/getoptionkit' => array(
            'pretty_version' => '2.6.0',
            'version' => '2.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../corneltek/getoptionkit',
            'aliases' => array(),
            'reference' => '995607ddf4fc90ebdb4a7d58fe972d581ad8495f',
            'dev_requirement' => false,
        ),
        'dflydev/dot-access-data' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-data',
            'aliases' => array(),
            'reference' => '3fbd874921ab2c041e899d044585a2ab9795df8a',
            'dev_requirement' => false,
        ),
        'dnoegel/php-xdg-base-dir' => array(
            'pretty_version' => 'v0.1.1',
            'version' => '0.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dnoegel/php-xdg-base-dir',
            'aliases' => array(),
            'reference' => '8f8a6e48c5ecb0f991c2fdcf5f154a47d85f9ffd',
            'dev_requirement' => false,
        ),
        'drush/drush' => array(
            'pretty_version' => '8.4.10',
            'version' => '8.4.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drush/drush',
            'aliases' => array(),
            'reference' => 'cecfcdb626144b7d13085096f0507f7c117a05b1',
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.0.0',
            'version' => '5.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'reference' => '9984a4d3a32ae7673d6971ea00bae9d0a1abba0e',
            'dev_requirement' => false,
        ),
        'geo6/geocoder-php-addok-provider' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geo6/geocoder-php-addok-provider',
            'aliases' => array(),
            'reference' => '5030967a6cdf6a29c5e9b08c78c2f2ddb68587c0',
            'dev_requirement' => false,
        ),
        'geocoder-php/common-http' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/common-http',
            'aliases' => array(),
            'reference' => '8e666f89d0b87121595ec2f5134a9f54bf4b0cd2',
            'dev_requirement' => false,
        ),
        'geocoder-php/free-geoip-provider' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/free-geoip-provider',
            'aliases' => array(),
            'reference' => '8f61d1729440e5fe8391ec7bb9dd42c8b3d2e055',
            'dev_requirement' => false,
        ),
        'geocoder-php/google-maps-provider' => array(
            'pretty_version' => '4.6.0',
            'version' => '4.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/google-maps-provider',
            'aliases' => array(),
            'reference' => '1e88138b66bf31b7e025b7bd579edb2cc9690414',
            'dev_requirement' => false,
        ),
        'geocoder-php/here-provider' => array(
            'pretty_version' => '0.6.0',
            'version' => '0.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/here-provider',
            'aliases' => array(),
            'reference' => 'd6b96e1bf5824714cbaea3486edd5b53956173dd',
            'dev_requirement' => false,
        ),
        'geocoder-php/mapquest-provider' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/mapquest-provider',
            'aliases' => array(),
            'reference' => '8c7b4b415bb606d6dbb7e6c61233be25f4bfe10b',
            'dev_requirement' => false,
        ),
        'geocoder-php/nominatim-provider' => array(
            'pretty_version' => '5.4.0',
            'version' => '5.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geocoder-php/nominatim-provider',
            'aliases' => array(),
            'reference' => '80f39ce41bcd0e4d9de3e83c40caf92d089fecf2',
            'dev_requirement' => false,
        ),
        'geocoder-php/provider-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'geoip2/geoip2' => array(
            'pretty_version' => 'v2.9.0',
            'version' => '2.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../geoip2/geoip2',
            'aliases' => array(),
            'reference' => 'a807fbf65212eef5d8d2db1a1b31082b53633d77',
            'dev_requirement' => false,
        ),
        'google/apiclient' => array(
            'pretty_version' => 'v2.4.1',
            'version' => '2.4.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/apiclient',
            'aliases' => array(),
            'reference' => '1fdfe942f9aaf3064e621834a5e3047fccb3a6da',
            'dev_requirement' => false,
        ),
        'google/apiclient-services' => array(
            'pretty_version' => 'v0.64',
            'version' => '0.64.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/apiclient-services',
            'aliases' => array(),
            'reference' => '0250aa8cadbe58e790aa07d736b675f3bdd87a1c',
            'dev_requirement' => false,
        ),
        'google/auth' => array(
            'pretty_version' => 'v1.3.2',
            'version' => '1.3.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../google/auth',
            'aliases' => array(),
            'reference' => '436007a77fd2037f933d3a5c8e4c7e0c9b88a7b0',
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '6.5.5',
            'version' => '6.5.5.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'reference' => '9d4290de1cfd701f38099ef7e183b64b4b7b0c5e',
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'reference' => 'a59da6cf61d80060647ff4d3eb2c03a2bc694646',
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'reference' => '239400de7a173fe9901b9ac7c06497751f00727a',
            'dev_requirement' => false,
        ),
        'jackgleeson/stats-collector' => array(
            'pretty_version' => 'v1.4.11',
            'version' => '1.4.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jackgleeson/stats-collector',
            'aliases' => array(),
            'reference' => '5d6e1a8b58bea5c06e63841a7187cb961272a9f2',
            'dev_requirement' => false,
        ),
        'league/csv' => array(
            'pretty_version' => '9.3.0',
            'version' => '9.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/csv',
            'aliases' => array(),
            'reference' => 'd16f85d1f958a765844db4bc7174017edf2dd637',
            'dev_requirement' => false,
        ),
        'maxmind-db/reader' => array(
            'pretty_version' => 'v1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind-db/reader',
            'aliases' => array(),
            'reference' => 'e042b4f8a2dff41e19019faf16427178b07fbd58',
            'dev_requirement' => false,
        ),
        'maxmind/minfraud' => array(
            'pretty_version' => 'v1.7.0',
            'version' => '1.7.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind/minfraud',
            'aliases' => array(),
            'reference' => 'fe7d66fa1d004c13a88fb3b98ca00af7e311a854',
            'dev_requirement' => false,
        ),
        'maxmind/web-service-common' => array(
            'pretty_version' => 'v0.5.0',
            'version' => '0.5.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maxmind/web-service-common',
            'aliases' => array(),
            'reference' => '61a9836fa3bb1743ab89752bae5005d71e78c73b',
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'reference' => '1cb1cde8e8dd0f70cc0fe51354a59acad9302084',
            'dev_requirement' => false,
        ),
        'mrmarkfrench/silverpop-php-connector' => array(
            'pretty_version' => '1.5.3',
            'version' => '1.5.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mrmarkfrench/silverpop-php-connector',
            'aliases' => array(),
            'reference' => '60d272707c52adf474c53d8236b0d06f1604294c',
            'dev_requirement' => false,
        ),
        'neitanod/forceutf8' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../neitanod/forceutf8',
            'aliases' => array(),
            'reference' => '47c883ab2739e7938a8bb0bfd1c29d48c88858de',
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v4.4.0',
            'version' => '4.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'reference' => 'bd43ec7152eaaab3bd8c6d0aa95ceeb1df8ee120',
            'dev_requirement' => false,
        ),
        'omnimail/omnimail' => array(
            'pretty_version' => '0.3.5.1',
            'version' => '0.3.5.1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../omnimail/omnimail',
            'aliases' => array(),
            'reference' => '96a129e651be24fc7cd7a34b2b7cfdb343333e11',
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v2.0.17',
            'version' => '2.0.17.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'reference' => '29af24f25bab834fcbb38ad2a69fa93b867e070d',
            'dev_requirement' => false,
        ),
        'pear/console_table' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_table',
            'aliases' => array(),
            'reference' => '1930c11897ca61fd24b95f2f785e99e0f36dcdea',
            'dev_requirement' => false,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/discovery' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/discovery',
            'aliases' => array(),
            'reference' => '9a6cb24de552bfe1aa9d7d1569e2d49c5b169a33',
            'dev_requirement' => false,
        ),
        'php-http/guzzle6-adapter' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/guzzle6-adapter',
            'aliases' => array(),
            'reference' => 'a56941f9dc6110409cfcddc91546ee97039277ab',
            'dev_requirement' => false,
        ),
        'php-http/httplug' => array(
            'pretty_version' => 'v1.1.0',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/httplug',
            'aliases' => array(),
            'reference' => '1c6381726c18579c4ca2ef1ec1498fdae8bdf018',
            'dev_requirement' => false,
        ),
        'php-http/message' => array(
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message',
            'aliases' => array(),
            'reference' => '2edd63bae5f52f79363c5f18904b05ce3a4b7253',
            'dev_requirement' => false,
        ),
        'php-http/message-factory' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/message-factory',
            'aliases' => array(),
            'reference' => 'a478cb11f66a6ac48d8954216cfed9aa06a501a1',
            'dev_requirement' => false,
        ),
        'php-http/message-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'php-http/promise' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-http/promise',
            'aliases' => array(),
            'reference' => 'dc494cdc9d7160b9a09bd5573272195242ce7980',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.5.1',
            'version' => '6.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'dd803df5ad7492e1b40637f7ebd258fee5ca7355',
            'dev_requirement' => false,
        ),
        'phpseclib/phpseclib' => array(
            'pretty_version' => '2.0.31',
            'version' => '2.0.31.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpseclib/phpseclib',
            'aliases' => array(),
            'reference' => '233a920cb38636a43b18d428f9a8db1f0a1a08f4',
            'dev_requirement' => false,
        ),
        'predis/predis' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../predis/predis',
            'aliases' => array(),
            'reference' => 'f0210e38881631afeafb56ab43405a92cafd9fd1',
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'reference' => '0f73288fd15629204f9d42b7055f72dacbe811fc',
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
                1 => '1.0',
            ),
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.10.3',
            'version' => '0.10.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'reference' => '2bde2fa03e05dff0aee834598b951d6fc7c6fe02',
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'dev_requirement' => false,
        ),
        'respect/validation' => array(
            'pretty_version' => '1.1.22',
            'version' => '1.1.22.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../respect/validation',
            'aliases' => array(),
            'reference' => '19d6ec893994912d21b390c43d287816ab070772',
            'dev_requirement' => false,
        ),
        'sgoettsch/monolog-rotating-file-handler' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sgoettsch/monolog-rotating-file-handler',
            'aliases' => array(),
            'reference' => '913e1de21981b252854e319549b5e1c450f5f22f',
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v3.4.39',
            'version' => '3.4.39.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'reference' => 'bf60d5e606cd595391c5f82bf6b570d9573fa120',
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v3.4.39',
            'version' => '3.4.39.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'reference' => 'ce9f3b5e8e1c50f849fded59b3a1b6bc3562ec29',
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v2.8.44',
            'version' => '2.8.44.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'reference' => '84ae343f39947aa084426ed1138bb96bf94d1f12',
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v3.4.39',
            'version' => '3.4.39.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => '5ec813ccafa8164ef21757e8c725d3a57da59200',
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'reference' => '3929d9fe8148d17819ad0178c748b8d339420709',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.22.1',
            'version' => '1.22.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'reference' => 'c6c942b1ac76c82448322025e084cadc56048b4e',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'reference' => '5dcab1bc7146cf8c1beaa4502a3d9be344334251',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'reference' => '37078a8dd4a2a1e9ab0231af7c6cb671b2ed5a7e',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.9.0',
            'version' => '1.9.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => 'd0cd638f4634c16d8df4508e847f14e9e43168b8',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php54' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php55' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php70' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php70',
            'aliases' => array(),
            'reference' => '0dd93f2c578bdc9c72697eaa5f1dd25644e618d3',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.18.1',
            'version' => '1.18.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'reference' => '639447d008615574653fb3bc60d1986d7172eaae',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.24.0',
            'version' => '1.24.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => '57b712b08eddb97c762a8caa32c84e037892d2e9',
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v4.4.36',
            'version' => '4.4.36.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'reference' => 'a35d6b8f82e2272504f23a267de49b8717ca0028',
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v3.4.39',
            'version' => '3.4.39.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'reference' => '13c03169ae485fc7f1a5143256622ce1bd3c77eb',
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v3.4.31',
            'version' => '3.4.31.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'reference' => '3dc414b7db30695bae671a1d86013d03f4ae9834',
            'dev_requirement' => false,
        ),
        'theiconic/name-parser' => array(
            'pretty_version' => 'v1.2.11',
            'version' => '1.2.11.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theiconic/name-parser',
            'aliases' => array(),
            'reference' => '9a54a713bf5b2e7fd990828147d42de16bf8a253',
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v1.44.2',
            'version' => '1.44.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'reference' => '138c493c5b8ee7cff3821f80b8896d371366b5fe',
            'dev_requirement' => false,
        ),
        'webflo/drupal-finder' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webflo/drupal-finder',
            'aliases' => array(),
            'reference' => '123e248e14ee8dd3fbe89fb5a733a6cf91f5820e',
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'reference' => '0df1908962e7a3071564e857d86874dad1ef204a',
            'dev_requirement' => false,
        ),
        'webmozart/path-util' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/path-util',
            'aliases' => array(),
            'reference' => 'd939f7edc24c9a1bb9c0dee5cb05d8e859490725',
            'dev_requirement' => false,
        ),
        'wikimedia/civicrm-data-table-provider' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/civicrm-data-table-provider',
            'aliases' => array(),
            'reference' => '45bb6ee2152b930594203ef637621dc7cc996718',
            'dev_requirement' => false,
        ),
        'wikimedia/composer-merge-plugin' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../wikimedia/composer-merge-plugin',
            'aliases' => array(),
            'reference' => '8ca2ed8ab97c8ebce6b39d9943e9909bb4f18912',
            'dev_requirement' => false,
        ),
        'wikimedia/donation-interface' => array(
            'pretty_version' => 'v2.5.7.1',
            'version' => '2.5.7.1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/donation-interface',
            'aliases' => array(),
            'reference' => 'b37f4732d810d1bd46a529603afef7fa65127b30',
            'dev_requirement' => false,
        ),
        'wikimedia/fundraising-crm' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => 'f3dd3921b274fff1b22a8e73d433c7a9b2bf9e63',
            'dev_requirement' => false,
        ),
        'wikimedia/omnimail-silverpop' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/omnimail-silverpop',
            'aliases' => array(),
            'reference' => '421eceb7845cfafd1ea53042e5a7dfde016225a9',
            'dev_requirement' => false,
        ),
        'wikimedia/smash-pig' => array(
            'pretty_version' => 'v0.7.9.3',
            'version' => '0.7.9.3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../wikimedia/smash-pig',
            'aliases' => array(),
            'reference' => 'ce2ca1971f1704b33bb3b3a5a9e3b92b1f236054',
            'dev_requirement' => false,
        ),
        'willdurand/geocoder' => array(
            'pretty_version' => '4.4.0',
            'version' => '4.4.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/geocoder',
            'aliases' => array(),
            'reference' => '3e86f5b10ab0cef1cf03f979fe8e34b6476daff0',
            'dev_requirement' => false,
        ),
    ),
);
